
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["400", "700"], 
  subsets: ["latin"],
  variable: "--font-poppins",
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
